INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_COMPANY,EMPLOYEE_NAME,ADDRESSENTITY_HOUSENUMBER)
VALUES(23L,'umar','deolite',null);
INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_COMPANY,EMPLOYEE_NAME,ADDRESSENTITY_HOUSENUMBER)
VALUES(24L,'ram','dell',null);