INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_COMPANY,EMPLOYEE_NAME,EMPLOYEE_PHONE_NUMBER)
VALUES(23L,'umar','deolite','9505315346');
INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_COMPANY,EMPLOYEE_NAME,EMPLOYEE_PHONE_NUMBER)
VALUES(24L,'ram','dell','9505315346');