INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_COMPANY,EMPLOYEE_COUNTRY,EMPLOYEE_NAME)
VALUES(23L,'umar','deolite','india');
INSERT INTO EMPLOYEE(EMPLOYEE_ID,EMPLOYEE_COMPANY,EMPLOYEE_COUNTRY,EMPLOYEE_NAME)
VALUES(24L,'ram','dell','india');