spring:
  datasource: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb 
    username: sa 
    password: sa 
management:
  server:
    port: 9090
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always   
  h2: 
    console: 
      enabled: true
logging:
  level:
    root: INFO
    org.springframework: INFO
 
     